using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using InkyCal.Models;
using InkyCal.Utils;
using Microsoft.AspNetCore.Mvc;
using SixLabors.Fonts;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Drawing.Processing;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp.Processing.Processors.Quantization;

namespace InkyCal.Server.Controllers
{
	/// <summary>
	/// A helper class for converting images to <see cref="ActionResult"/>s.
	/// </summary>
	internal static class ImageExtensions
	{

		/// <summary>
		/// Returns a <see cref="FileContentResult"/> from an image, generated by <see cref="IPanelRenderer.GetImage"/>
		/// </summary>
		/// <param name="controller"></param>
		/// <param name="image"></param>
		/// <param name="colors"></param>
		/// <param name="cancellationToken"></param>
		/// <returns></returns>
		public static async Task<ActionResult> Image(this ControllerBase controller, Image image, ReadOnlyMemory<Color> colors, CancellationToken cancellationToken)
		{
			ArgumentNullException.ThrowIfNull(controller);
			ArgumentNullException.ThrowIfNull(image);

			using var stream = new MemoryStream();
			await image.SaveAsGifAsync(stream, new (){ Quantizer = new PaletteQuantizer(colors) }, cancellationToken);

			return controller.File(
				fileContents: stream.ToArray(),
				contentType: "image/gif");
		}

		/// <summary>
		/// Returns a <see cref="FileContentResult"/> from a <see cref="IPanelRenderer"/> for the specified <paramref name="model"/>.
		/// </summary>
		/// <param name="controller"></param>
		/// <param name="renderer"></param>
		/// <param name="model"></param>
		/// <param name="cancellationToken"></param>
		/// <param name="requestedWidth"></param>
		/// <param name="requestedHeight"></param>
		/// <param name="rotateMode"></param>
		/// <returns></returns>
		public static async Task<ActionResult> Image(this ControllerBase controller,
											   IPanelRenderer renderer,
											   DisplayModel model,
											   CancellationToken cancellationToken,
											   int? requestedWidth = null,
											   int? requestedHeight = null,
											   RotateMode rotateMode = RotateMode.None)
		{
			model.GetSpecs(out var defaultWidth, out var defaultHeight, out var colors);

			var flip = false;

			int width, height;


			switch (rotateMode)
			{
				case RotateMode.Rotate270:
				case RotateMode.Rotate90:
					height = requestedWidth ?? defaultWidth;
					width = requestedHeight ?? defaultHeight;
					break;
				default:
					width = requestedWidth ?? defaultWidth;
					height = requestedHeight ?? defaultHeight;
					break;
			}

			switch (rotateMode)
			{
				case RotateMode.Rotate270:
				case RotateMode.Rotate180:
					flip = true;
					break;
			}

			//NB: Web-based requests will specify portrait oriented dimensions.
			//    GetSpecs get landscape-oriented dimensions
			//    Therefore flip-em!
			return await controller.Image(renderer, width, height, colors, flip, cancellationToken);
		}


		/// <summary>
		/// Returns a <see cref="FileContentResult"/> from <see cref="IPanelRenderer.GetImage"/> with specific dimensions and color space.
		/// </summary>
		/// <param name="controller"></param>
		/// <param name="panelRenderer"></param>
		/// <param name="width"></param>
		/// <param name="height"></param>
		/// <param name="colors"></param>
		/// <param name="flip"></param>
		/// <param name="cancellationToken"></param>
		/// <returns></returns>
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>")]
		public static async Task<ActionResult> Image(
			this ControllerBase controller,
			IPanelRenderer panelRenderer,
			int width,
			int height,
			Color[] colors,
			bool flip,
			CancellationToken cancellationToken)
		{
			if (panelRenderer is null)
				throw new ArgumentNullException(nameof(panelRenderer));

			try
			{
				var bytes = await panelRenderer.GetCachedImage(width, height, colors, log: controller.ConditionalLog);

				if (flip)
				{
					using var image = SixLabors.ImageSharp.Image.Load<Rgba32>(bytes);
					image.Mutate(x => x.Rotate(RotateMode.Rotate180));
					return await controller.Image(image, colors, cancellationToken);
				}
				else
					return controller.Gif(bytes);
			}
			catch (Exception ex)
			{

				ex.Data["PanelRendererType"] = panelRenderer.GetType().Name;
				ex.Log();

				colors.ExtractMeaningFullColors(
					 out var primaryColor
					, out var supportColor
					, out var errorColor
					, out var backgroundColor
					);

				using var image = PanelRenderingHelper.CreateImage(width, height, backgroundColor);
				image.Mutate(x =>
					{
						var messageFont = FontHelper.NotoSans.CreateFont(16);
						var textOption = new RichTextOptions(messageFont)
						{
							WrappingLength = width,
							Font = messageFont
						};
						//var errorMessageRenderOptions = errorTextOptions.ToRendererOptions(messageFont);
						var errorMessage = ex.Message.ToSafeChars(FontHelper.NotoSans).Trim();

						x.DrawText(textOption, errorMessage, errorColor);

						var start = (int)TextMeasurer.MeasureBounds(errorMessage, textOption).Height
						+ 10;

						x.DrawText(
							textOptions: new(textOption) { Origin = new(x: 0, y: start) },
							text: ex.StackTrace,
							color: primaryColor);
					});
				return await controller.Image(image, colors, cancellationToken);
			}
		}

		/// <summary>
		/// Returns a <see cref="FileContentResult"/> from , generated by <see cref="IPanelRenderer.GetImage"/>
		/// </summary>
		/// <param name="controller"></param>
		/// <param name="image"></param>
		/// <returns></returns>
		public static ActionResult Gif(this ControllerBase controller, byte[] image)
		{
			ArgumentNullException.ThrowIfNull(controller);
			ArgumentNullException.ThrowIfNull(image);

			return controller.File(
				fileContents: image,
				contentType: "image/gif");
		}

		private static async Task ConditionalLog(this ControllerBase controller, Exception ex, bool handled = false, string explanation = null)
		{
			if (handled)
				Console.WriteLine($"{explanation ?? "Handled exception"}: {ex.Message}");
			else
			{
				var user = await controller.GetAuthenticatedUser();
				ex.Log(user);
			}
		}
	}
}
