apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: incididunt nulla
stringData:
  cloudflare_tunnel_token: eyJhIjoiZDFmZjg3ZjRhZTg1NjYwMjQ4NDRhODljNTFjYjBjNzciLCJ0IjoiNDRkYWQ2MmYtOGY5MS00MzllLThjZDctNGQ1NWRhZTEwZjE2IiwicyI6IllqUm1OelE1TW1RdE16a3pNUzAwTWpBeUxXRTBNbUl0TW1RMlptVTJPV05qTmpjMyJ9
  adipisicing_63: 36314681.14311877
  ina96: laboris Excepteur eiusmod non elit
immutable: true
data:
  Duis_15: esse fugiat qui
  in2ca: false
  idd: sed ad exercitation
