<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<Features>flow-analysis</Features>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	<WarningsAsErrors />
	<NoWarn />
	<UserSecretsId>ef330956-86ef-4986-bab6-740de0fbd262</UserSecretsId>
	<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup> 
	<Compile Remove="Controllers\GoogleController.cs" />
  </ItemGroup>

  <ItemGroup>
	<Content Include="..\changelog.md" Link="changelog.md">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</Content>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
	<PackageReference Include="Bugsnag.AspNet.Core" Version="4.1.0" />
	<PackageReference Include="Humanizer" Version="3.0.10" />
	<PackageReference Include="Magick.NET.Core" Version="14.10.4" />
	<PackageReference Include="Markdig.Signed" Version="1.1.1" />
	<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.3" />
	<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.5" />
	<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.103">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
	<PackageReference Include="MiniProfiler.AspNetCore.Mvc" Version="4.5.4" />
	<PackageReference Include="MiniProfiler.EntityFrameworkCore" Version="4.5.4" />
	<PackageReference Include="Sentry.AspNetCore" Version="6.1.0" />
	<PackageReference Include="SonarAnalyzer.CSharp" Version="10.20.0.135146">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
	<PackageReference Include="System.Runtime.Caching" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\InkyCal.Data\InkyCal.Data.csproj" />
	<ProjectReference Include="..\InkyCal.Models\InkyCal.Models.csproj" />
	<ProjectReference Include="..\InkyCal.Server.Config\InkyCal.Server.Config.csproj" />
	<ProjectReference Include="..\InkyCal.Utils\InkyCal.Utils.csproj" />
  </ItemGroup>

</Project>
