<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<IsPackable>false</IsPackable>
	<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.102">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
	<PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
	<PackageReference Include="coverlet.collector" Version="6.0.4">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="SonarAnalyzer.CSharp" Version="10.19.0.132793">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="xunit" Version="2.9.3" />
	<PackageReference Include="xunit.analyzers" Version="1.27.0">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="XunitXml.TestLogger" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\InkyCal.Models\InkyCal.Models.csproj" />
  </ItemGroup>

</Project>
