<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<IsPackable>false</IsPackable>
	<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
	<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	<OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.202">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="coverlet.collector" Version="8.0.1">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="1.9.1" />
	<PackageReference Include="SonarAnalyzer.CSharp" Version="10.23.0.137933">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\InkyCal.Models\InkyCal.Models.csproj" />
  </ItemGroup>

</Project>
