<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<IsPackable>false</IsPackable>
	<UserSecretsId>ef330956-86ef-4986-bab6-740de0fbd262</UserSecretsId>
	<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
	<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
	<Content Include="..\InkyCal.Server\appsettings.json" Link="appsettings.json">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</Content>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.202">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
	<PackageReference Include="MiniProfiler.EntityFrameworkCore" Version="4.5.4" />
	<PackageReference Include="MiniProfiler.Shared" Version="4.5.4" />
	<PackageReference Include="MSTest.TestAdapter" Version="4.2.3" />
	<PackageReference Include="MSTest.TestFramework" Version="4.2.3" />
	<PackageReference Include="coverlet.collector" Version="8.0.1">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="SonarAnalyzer.CSharp" Version="10.23.0.137933">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="xunit" Version="2.9.3" />
	<PackageReference Include="xunit.analyzers" Version="1.27.0">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Xunit.SkippableFact" Version="1.5.61" />
	<PackageReference Include="XunitXml.TestLogger" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\InkyCal.Data\InkyCal.Data.csproj" />
  </ItemGroup>

</Project>
