name: Build Docker image

on:
  # Nightly build - pull base image
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-docker:
    uses: ./.github/workflows/build-docker-image-reusable.yml