name: Build Docker image

on:
  workflow_call:
    outputs:
      docker_image_name:
        description: 'The name of the Docker image'
        value: ${{ jobs.build-docker.outputs.docker_image_name }}

jobs:
  build-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    outputs:
      docker_image_name: ${{ steps.docker_image_name.outputs.value }}
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Sets env vars for release
      run: |
          echo "DOCKER_IMAGE_NAME=latest >> $GITHUB_ENV
      if: ${{ steps.extract_branch.outputs.branch == 'develop' }}

    # This step is run when the tag is staging-XXX
    - name: Sets env vars for staging
      run: |
          echo "DOCKER_IMAGE_NAME=${{ steps.extract_branch.outputs.branch }}" >> $GITHUB_ENV
      if: ${{ steps.extract_branch.outputs.branch != 'develop' }}

    - name: Replace slashes with underscores in DOCKER_IMAGE_NAME
      id: findandreplace_branchname
      uses: mad9000/actions-find-and-replace-string@5
      with:
        source: ${{env.DOCKER_IMAGE_NAME}} # this translates to ref/heads/main on the main branch, but can be any arbitrary string 
        find: '/'        # we want to remove ref/heads/ from source 
        replace: '_'     # and replace it with an underscore
      
    - name: Concatenate strings
      id: docker_image_name
      run: echo "value=atreyu/inkycal.server:${{ steps.findandreplace_branchname.outputs.value }}" >> $GITHUB_OUTPUT

    - name: Update DOCKER_IMAGE_NAME
      run: |
          echo "DOCKER_IMAGE_NAME=${{ steps.docker_image_name.outputs.value }}" >> $GITHUB_ENV
 
    # - name: Build Docker image
    #   # You may pin to the exact commit or the version.
    #   uses: docker/build-push-action@v6
    #   with:
    #     # context: .
    #     load: true # Load the image in Docker, for scanning and pushing
    #     sbom: true
    #     push: false
    #     tags: atreyu/inkycal.server:${{env.DOCKER_IMAGE_NAME}}

    
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Build and store local image
      run: docker build -t ${{env.DOCKER_IMAGE_NAME}} .

    - name: List local Docker images
      run: docker images

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@0.29.0
      with:
        image-ref: ${{env.DOCKER_IMAGE_NAME}}
        format: 'sarif'
        output: 'trivy-results.sarif'
        cache: 'false' # Prevents hitting rate limit: https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#cache
    
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'


