name: Build and test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Builds and tests libraries & app
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          7.0.x
          
    # See also DockerFile
    - name: Install Ghostscript (for rendering PDFs)
      run: sudo apt-get install -y ghostscript
    
    - name: Install Time Zone data
      run: sudo apt-get install -y tzdata
    
    #- name: Addresses Database Globalization issues
    #  run: sudo apt-get install -y icu-libs
      
    - name: Install dependencies
      run: dotnet restore InkyCal.sln

    - name: Build
      run: dotnet build InkyCal.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test InkyCal.sln --no-restore --verbosity detailed --logger "trx;LogFileName=test-results.trx"

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: testresults
        path: '**/*.trx'
        retention-days: 1

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
          name: Dotnet testresult # Name of the check run which will be created
          path: '**/*.trx'        # All test results
          reporter: dotnet-trx    # Format of test results

  build-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Build Docker image
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@ab83648e2e224cfeeab899e23b639660765c3a89
      uses: docker/build-push-action@v4
      with:
        push: false
        tags: atreyu/inkycal.server:latest

  publish:
    name: Publish to docker.io
    runs-on: ubuntu-latest
    needs: [build, build-docker]
    steps:
    - name: Docker Login
      # You may pin to the exact commit or the version.
      uses: docker/login-action@v2
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # registry: # optional
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }} # optional
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Log out from the Docker registry at the end of a job
        # logout: # optional, default is true

    - name: Push Docker image
      # You may pin to the exact commit or the version.
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: atreyu/inkycal.server:latest